// Generated by CoffeeScript 1.6.3
(function() {
  var colors, compile, debug, fs, i, idtm, parser, util;

  fs = require('fs');

  util = require('util');

  colors = require('colors');

  parser = require('../js/parser');

  idtm = require('../js/idtm');

  compile = require('../ws/compile');

  debug = false;

  i = process.argv.indexOf("--debug");

  if (i >= 0) {
    process.argv.splice(i, 1);
    debug = true;
  }

  fs.readFile(process.argv[2], {
    encoding: "utf8"
  }, function(err, data) {
    var compiler, compiler2, op, p, result, result2, sts, _i, _len, _results;
    if (err != null) {
      throw err;
    }
    p = new parser.JSParser;
    sts = p.parse(data);
    compiler = new idtm.Compiler;
    result = compiler.compile(sts);
    if (debug) {
      console.log(util.inspect(result, {
        depth: 4
      }).grey);
    }
    compiler2 = new compile.Compiler;
    result2 = compiler2.compile(result);
    _results = [];
    for (_i = 0, _len = result2.length; _i < _len; _i++) {
      op = result2[_i];
      _results.push(process.stdout.write(op.getCode()));
    }
    return _results;
  });

}).call(this);
