// Generated by CoffeeScript 1.6.3
(function() {
  var bufs, operations;

  operations = require('./operations');

  bufs = [];

  process.stdin.resume();

  /*
  process.stdin.on "readable",->
      bufs.push process.stdin.read()
  */


  process.stdin.on("data", function(chunk) {
    return bufs.push(chunk);
  });

  process.stdin.on("end", function() {
    var all, char, ops, _i;
    all = Buffer.concat(bufs);
    ops = [];
    ops.push(new operations.stack.Push(0));
    for (_i = all.length - 1; _i >= 0; _i += -1) {
      char = all[_i];
      ops.push(new operations.stack.Push(char));
    }
    ops.push(new operations.flow.Label(" "));
    ops.push(new operations.stack.Duplicate);
    ops.push(new operations.flow.JumpZero("\t"));
    ops.push(new operations.io.OutputChar);
    ops.push(new operations.flow.Jump(" "));
    ops.push(new operations.flow.Label("\t"));
    ops.push(new operations.flow.End);
    return process.stdout.write(ops.map(function(x) {
      return x.getCode();
    }).join(""));
  });

}).call(this);
